language: node_js

node_js:
  - "6"
  
script:
  - npm test

after_success:
  - npm install -g istanbul codecov
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov
  
branches:
  only:
    - master